// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBK0Yy8SB6dDDBsdJHCs2JAccEEOFpOOA',
    appId: '1:110572797203:web:ad6ee1916a6d1d36ab6ee6',
    messagingSenderId: '110572797203',
    projectId: 'educonnect-5d80c',
    authDomain: 'educonnect-5d80c.firebaseapp.com',
    storageBucket: 'educonnect-5d80c.firebasestorage.app',
    measurementId: 'G-QNJV7ZVQYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjQVV3Mb0r4yDyjf3XTyw13hFxR44xXG8',
    appId: '1:110572797203:android:ac0546deb9e34623ab6ee6',
    messagingSenderId: '110572797203',
    projectId: 'educonnect-5d80c',
    storageBucket: 'educonnect-5d80c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD613C938Ze4K2XltgiOzTPLiQSPzJJFgA',
    appId: '1:110572797203:ios:0b0c86f45f06c130ab6ee6',
    messagingSenderId: '110572797203',
    projectId: 'educonnect-5d80c',
    storageBucket: 'educonnect-5d80c.firebasestorage.app',
    iosBundleId: 'com.example.smartClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD613C938Ze4K2XltgiOzTPLiQSPzJJFgA',
    appId: '1:110572797203:ios:0b0c86f45f06c130ab6ee6',
    messagingSenderId: '110572797203',
    projectId: 'educonnect-5d80c',
    storageBucket: 'educonnect-5d80c.firebasestorage.app',
    iosBundleId: 'com.example.smartClass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBK0Yy8SB6dDDBsdJHCs2JAccEEOFpOOA',
    appId: '1:110572797203:web:fb396c88eab503e3ab6ee6',
    messagingSenderId: '110572797203',
    projectId: 'educonnect-5d80c',
    authDomain: 'educonnect-5d80c.firebaseapp.com',
    storageBucket: 'educonnect-5d80c.firebasestorage.app',
    measurementId: 'G-F3284EVWBQ',
  );
}
